//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcedureStockee.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produit
    {
        public int Id { get; set; }
        public string Designation { get; set; }
        public int CategorieId { get; set; }
        public System.DateTime DateAchat { get; set; }
        public int QteMin { get; set; }
        public double Prix { get; set; }
        public bool IsBio { get; set; }
        public string Fournisseur { get; set; }
        public string Description { get; set; }
        public int SeasonId { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Season Season { get; set; }
    }
}
