//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcedureStockee.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VRequete
    {
        public int Id { get; set; }
        public string Design { get; set; }
        public string CatName { get; set; }
        public string SeasonName { get; set; }
    }
}
