// <auto-generated />
using CodeFirstManyToManyCas1.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CodeFirstManyToManyCas1.Migrations
{
    [DbContext(typeof(ClubDBContext))]
    partial class ClubDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ActiviteAdherent", b =>
                {
                    b.Property<int>("ActivitesId")
                        .HasColumnType("int");

                    b.Property<int>("AdherentsId")
                        .HasColumnType("int");

                    b.HasKey("ActivitesId", "AdherentsId");

                    b.HasIndex("AdherentsId");

                    b.ToTable("ActiviteAdherent");
                });

            modelBuilder.Entity("CodeFirstManyToManyCas1.Model.Activite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Activites");
                });

            modelBuilder.Entity("CodeFirstManyToManyCas1.Model.Adherent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adresse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Adherents");
                });

            modelBuilder.Entity("ActiviteAdherent", b =>
                {
                    b.HasOne("CodeFirstManyToManyCas1.Model.Activite", null)
                        .WithMany()
                        .HasForeignKey("ActivitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CodeFirstManyToManyCas1.Model.Adherent", null)
                        .WithMany()
                        .HasForeignKey("AdherentsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
